### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by EphraimBane** [ThatNerdyPikachu/nspbuild#8]
I get an error when I try to create an NSP.
`panic: exit status 1

goroutine 1 [running]:
main.chkErr(...)
        C:/Users/Riley/go/src/github.com/ThatNerdyPikachu/nspbuild/utils.go:94
main.main()
        C:/Users/Riley/go/src/github.com/ThatNerdyPikachu/nspbuild/main.go:195 +0x1b75`

**Comment by SegFault42** [comment]
It's probably because you have entered a wrong hex value.

Valid range is between 0100000000000000 and 01FFFFFFFFFFFFFF
